# Configuration for generating a static compilation figure
dataset_params: "/home/david/Documents/odometry/submodules/mmwave_radar_processing/gui_configs/dataset_params_IcaRAus.yaml"
processor_params: "/home/david/Documents/odometry/submodules/mmwave_radar_processing/gui_configs/processor_params.yaml"
# dataset_path: "/home/david/Documents/odometry/..." # Optional override
# config_name: "config.cfg" # Optional override
frame_to_run: 297
display_in_dB: true
processors_to_display:
  - "range_angle_resp"
  - "doppler_azimuth_resp"
  - "range_doppler_resp"
  - "range_resp"
output_filename: "compilation_frame_297.png"
