# Configuration for generating a static compilation figure
dataset_params: "/home/david/Documents/odometry/submodules/mmwave_radar_processing/gui_configs/dataset_params_IcaRAus.yaml"
processor_params: "/home/david/Documents/odometry/submodules/mmwave_radar_processing/gui_configs/processor_params_6843_nominal.yaml"
# dataset_path: "/home/david/Documents/odometry/..." # Optional override
# config_name: "config.cfg" # Optional override
frame_to_run: 301
display_in_dB: true
processors_to_display:
  - "range_doppler_resp"
  - "range_doppler_detector_2d"
  - "range_resp"
  - "point_cloud_generator"
output_filename: "compilation_nominal_6843_3D.png"
