processors:
  range_angle_resp:
    num_angle_bins: 64
    rx_antennas: []
    chirp_idx: 0
  range_doppler_resp:
    rx_idx: 0
  micro_doppler_resp:
    target_ranges: [3.0, 3.7]
    num_frames_history: 20
    rx_idx: 0
  doppler_azimuth_resp:
    num_angle_bins: 64
    valid_angle_range: [-1.04719755, 1.04719755]
    min_zoom_fft_vel_span: 0.1
    rx_antennas: []
    range_window: []
    shift_angle: true
    use_precise_fft: false
    precise_vel_range: [-0.25, 0.25]
  range_resp:
    chirp_idx: 0
