datasets:
  - path: "/data/IcaRAus/datasets/UAV/Flow_datasets/vicon_diamond"
    name: "vicon_diamond_2_dark"
  - path: "/data/IcaRAus/datasets/UAV/Flow_datasets/vicon_diamond"
    name: "vicon_diamond_3_dark"

radar:
  config_file: "6843_RadVel_ods_10Hz.cfg"
  array_geometry: "ods"
  array_direction: "down"

processors:
  velocity_estimator:
    min_r2_threshold: 0.2
    min_inlier_percent: 0.5
    moving_window_size: 5
    z_score_threshold: 3.0
    min_std_dev: 0.2
    outlier_rejection_limit: 5
  
  point_cloud_generator:
    detector_type: "range_doppler_ground_detector"
    detector_params:
      vel_cfar_type: "os_cfar_1d"
      vel_cfar_params:
        num_train: 12
        num_guard: 4
        rho: 0.5
        alpha: 15
      altimeter_params:
        min_altitude_m: 25.0e-2
        zoom_search_region_m: 20.0e-2
        altitude_search_limit_m: 40.0e-2
        range_bias: 0.0
        precise_est_enabled: true
    az_antenna_idxs: [0, 3, 4, 7]
    el_antenna_idxs: [9, 8, 5, 4]
    shift_az_resp: true
    shift_el_resp: false

  virtual_array_reformatter: {}

analysis:
  error_method: "absolute"

transformation:
  uav_vel_radar_msmt: [[0, 1, 0], [0, 0, -1], [1, 0, 0]]
  odom_vel_matrix: [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
  vicon_vel_matrix: [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
